# Generated by Django 4.2.6 on 2023-11-04 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BRF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Building', models.CharField(max_length=48)),
            ],
        ),
        migrations.CreateModel(
            name='CTRF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cabinet_type', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='DRF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Discipline_name', models.CharField(max_length=48)),
            ],
        ),
        migrations.CreateModel(
            name='SRF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subject', models.CharField(max_length=64)),
            ],
        ),
    ]
