# Generated by Django 4.2.6 on 2023-11-04 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0002_brf_ctrf_drf_srf'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brf',
            old_name='Building',
            new_name='Building_name',
        ),
        migrations.RenameField(
            model_name='ctrf',
            old_name='Cabinet_type',
            new_name='Cabinet_type_name',
        ),
        migrations.RenameField(
            model_name='srf',
            old_name='Subject',
            new_name='Subject_name',
        ),
    ]
