# Generated by Django 4.2.6 on 2023-11-07 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0003_rename_building_brf_building_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CRF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Building', models.CharField(max_length=48)),
                ('Cabinet_number', models.IntegerField()),
                ('Cabinet_type', models.CharField(max_length=96)),
                ('Equipment', models.CharField(max_length=96)),
            ],
        ),
        migrations.RenameModel(
            old_name='SRF',
            new_name='ERF',
        ),
        migrations.RenameField(
            model_name='erf',
            old_name='Subject_name',
            new_name='Equipment_name',
        ),
        migrations.AlterField(
            model_name='trf',
            name='Name',
            field=models.CharField(max_length=36),
        ),
        migrations.AlterField(
            model_name='trf',
            name='Surname',
            field=models.CharField(max_length=36),
        ),
        migrations.AlterField(
            model_name='trf',
            name='Surname1',
            field=models.CharField(max_length=36),
        ),
    ]
