# Generated by Django 4.2.6 on 2023-11-10 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0004_crf_rename_srf_erf_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Connection_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_name', models.CharField(max_length=32)),
                ('db_user', models.CharField(choices=[('', ''), ('', 'student')], max_length=48)),
                ('db_password', models.CharField(choices=[('', ''), ('', '123456')], max_length=32)),
                ('db_host', models.GenericIPAddressField(choices=[('', ''), ('', 'localhost')])),
                ('db_port', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='crf',
            name='Building',
            field=models.CharField(choices=[('', 'Ильинка'), ('', 'Речная')], max_length=48),
        ),
    ]
