# Generated by Django 4.2.6 on 2023-11-10 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0005_connection_data_alter_crf_building'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection_data',
            name='db_host',
            field=models.GenericIPAddressField(choices=[('', ''), ('localhost', 'localhost')]),
        ),
        migrations.AlterField(
            model_name='connection_data',
            name='db_password',
            field=models.CharField(choices=[('', ''), ('123456', '123456')], max_length=32),
        ),
        migrations.AlterField(
            model_name='connection_data',
            name='db_user',
            field=models.CharField(choices=[('', ''), ('student', 'student')], max_length=48),
        ),
        migrations.AlterField(
            model_name='crf',
            name='Building',
            field=models.CharField(choices=[('Ильинка', 'Ильинка'), ('Речная', 'Речная')], max_length=48),
        ),
    ]
