# Generated by Django 4.2.6 on 2023-11-10 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0006_alter_connection_data_db_host_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection_data',
            name='db_host',
            field=models.GenericIPAddressField(choices=[('<django.db.models.fields.GenericIPAddressField>', ''), ('localhost', 'localhost')]),
        ),
    ]
