# Generated by Django 4.2.6 on 2023-11-10 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0007_alter_connection_data_db_host'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection_data',
            name='db_host',
            field=models.CharField(choices=[('<django.db.models.fields.GenericIPAddressField>', ''), ('localhost', 'localhost')], max_length=32),
        ),
    ]
